version: '3.8'
services:
  database:
    image: library/postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: iris
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: iris
