name: CI
on: [push]
jobs:
  build:
    name: build and verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: compile and test
        run: mvn -B clean verify --file pom.xml
      - name: static code analysis
        run: >
          mvn -B sonar:sonar --file pom.xml
          -Dsonar.projectKey=dimasmith_iris
          -Dsonar.organization=dimasmith
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
