name: CI
on: [push]
jobs:
  build:
    name: build and verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build and test
        uses: LucaFeger/action-maven-cli@1.1.0
        args: clean verify
